### ISSUE TITLE
Add example/expected inputs and outputs documentation

### ISSUE THREAD

**Issue by CremaLuca** [Slthy/Microplus-Lenex#12]
In una funzione come
https://github.com/Slthy/Microplus-Lenex/blob/b6380314e274b9a568c6320ebd00d117442f74a9/utils.py#L83-L85
non ricordo in che formato debba essere la stringa in ingresso e soprattutto non ho una idea del perché dai in output due pezzi di url.

Aggiungi un esempio di stringa in ingresso ed il motivo per cui le separi per facilitare la lettura, il te del futuro ti ringrazierà.

**Comment by Slthy** [comment]
vero, ho dovuto un attimo ragionarci per capire il perché di questa funzione
