### ISSUE TITLE
Why is the URL split?

### ISSUE THREAD

**Issue by CremaLuca** [Slthy/Microplus-Lenex#14]
Alla linea 12 di functions.py separi url in due variabili, `base_url` e `event`
https://github.com/Slthy/Microplus-Lenex/blob/b6380314e274b9a568c6320ebd00d117442f74a9/functions.py#L12-L14

ma poi usi le due variabili sempre insieme

https://github.com/Slthy/Microplus-Lenex/blob/b6380314e274b9a568c6320ebd00d117442f74a9/functions.py#L16

https://github.com/Slthy/Microplus-Lenex/blob/b6380314e274b9a568c6320ebd00d117442f74a9/functions.py#L18

https://github.com/Slthy/Microplus-Lenex/blob/b6380314e274b9a568c6320ebd00d117442f74a9/functions.py#L23

Come mai hai fatto la separazione?

**Comment by Slthy** [comment]
```py
url('https://fin2022.microplustiming.com/NU_2022_07_28-08_04_Roma_web.php')
>>> ['https://fin2022.microplustiming.com/export/NU_', '2022_07_28-08_04_Roma']
```

Separo l'url del frontend della competizione perché devo manipolarlo:
- Nella prima parte, viene aggiunto `/export/` al percorso di rete. Es: `https://fin2022.microplustiming.com/ >>> https://fin2022.microplustiming.com/export/`
- Nella seconda parte, tolgo il trailing `_web.php`

Effettivamente potrei togliere la funzione e mettere direttamente:
```py
url_elab = url.replace('/NU', '/export/NU').replace('_web.php', '')
```
