### ISSUE TITLE
Do not call f.close in "with-as"

### ISSUE THREAD

**Issue by CremaLuca** [Slthy/Microplus-Lenex#16]
Lo scopo della keyword `with` è esattamente quello di chiudere il file una volta finita l'indentazione.
https://github.com/Slthy/Microplus-Lenex/blob/b6380314e274b9a568c6320ebd00d117442f74a9/functions.py#L34-L36
Di conseguenza è buona norma non chiudere il file manualmente sia perché non serve sia perché se un giorno non dovessi accorgerti di aver chiamato f.close() ed aggiungessi altro codice dopo perderesti tempo a capire come mai il file è chiuso all'interno di un with statement.

È così anche in altri linguaggi di programmazione quindi stacci attento.

**Comment by Slthy** [comment]
yep, makes sense
