### ISSUE TITLE
Condition inversion/early return for clarity

### ISSUE THREAD

**Issue by CremaLuca** [Slthy/Microplus-Lenex#18]
In `utils.format_time` hai la seguente condizione

https://github.com/Slthy/Microplus-Lenex/blob/9e0c07df9bea626b55bf0dc7c8c8e563c21bbd53/utils.py#L90

Il codice continua di una indentazione per il percorso "felice" se va tutto bene, altrimenti restituisce `"NT"`

https://github.com/Slthy/Microplus-Lenex/blob/9e0c07df9bea626b55bf0dc7c8c8e563c21bbd53/utils.py#L96

Secondo me (e secondo altri con più esperienza nella programmazione) è meglio applicare quella che si chiama condition inversion, che consiste nel concentrare i casi "brutti" all'inizio del codice ed evitare una indentazione.

```py
# Time too short, invalid (e.g. "dnf")
if len(time) < 4:
    return "NT"

if len(time) > 5:
    ...
```

**Comment by Slthy** [comment]
vero, la funzione diventa più comoda da leggere

**Comment by CremaLuca** [comment]
No fra, non serve l'else dopo un return

**Comment by Slthy** [comment]
cazzo vero, stupid af
